language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
- npm install -g firebase-tools
script:
- firebase use staging
- npm run build:prod
deploy:
  - provider: script
    script: bash scripts/deploy.dev.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.mw.sh
    skip_cleanup: true
    on:
      branch: production-mw
  - provider: script
    script: bash scripts/deploy.prod.ke.sh
    skip_cleanup: true
    on:
      branch: production-ke            
