language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools

script:
  - firebase use staging
  - npm run build:prod

after_success:
  - firebase deploy - project extension-toolkit-staging - token $FIREBASE_TOKEN
