language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
- npm install -g firebase-tools
script:
- firebase use staging
- npm run build:prod
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  message: "Firebase deploy success"
  project: "extension-toolkit-staging"
