language: node_js
node_js:
- '10'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
- npm install -g firebase-tools
script:
# set branch assets - use bash command as .sh files may not be executable
- if [ "$TRAVIS_BRANCH" = "master" ]; then bash scripts/prepare.staging.sh; fi
- if [ "$TRAVIS_BRANCH" = "production-mw" ]; then bash scripts/prepare.mw.sh; fi
- if [ "$TRAVIS_BRANCH" = "production-ke" ]; then bash scripts/prepare.ke.sh; fi
# populate src/environments/base.ts with available production environment variables
- if [[ "$TRAVIS_BRANCH" = production-* ]]; then echo "production build" && npm run env:set; fi
# - cat ./src/environments/base.ts
- npm run build:prod
deploy:
  - provider: script
    script: bash scripts/deploy.staging.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.mw.sh
    skip_cleanup: true
    on:
      branch: production-mw
  - provider: script
    script: bash scripts/deploy.prod.ke.sh
    skip_cleanup: true
    on:
      branch: production-ke            
