language: node_js
node_js:
- '8'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_script:
- npm install -g firebase-tools
script:
# set branch assets
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./scripts/prepare.staging.sh; fi
- if [ "$TRAVIS_BRANCH" = "production-mw" ]; then ./scripts/prepare.mw.sh; fi
- if [ "$TRAVIS_BRANCH" = "production-ke" ]; then ./scripts/prepare.ke.sh; fi
- npm run build:prod
deploy:
  - provider: script
    script: bash scripts/deploy.staging.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy.prod.mw.sh
    skip_cleanup: true
    on:
      branch: production-mw
  - provider: script
    script: bash scripts/deploy.prod.ke.sh
    skip_cleanup: true
    on:
      branch: production-ke            
