language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
 — npm install -g firebase-tools

script:
  — firebase use staging
  — npm run build:prod
  — firebase deploy — project extension-toolkit-staging — token $FIREBASE_TOKEN.